name: Sphinx-Documentation

on:
    push:
        branches: ["main", "docs"]
    pull_request:
        branches: ["main"]

jobs:
    build_docs:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        env:
            GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Set up Python 3.11.2
              uses: actions/setup-python@v3
              with:
                  python-version: "3.11.2"

            - name: Install Dependencies
              run: |
                  python -m pip install --upgrade pip
                  python -m pip install -U sphinx
                  python -m pip install sphinx_rtd_theme

            - name: Generate Docs
              working-directory: docs
              run: |
                  make html

            - name: Deploy to Github Pages
              uses: peaceiris/actions-gh-pages@v3
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_dir: _build/html
